'use strict';

angular.module('basic').config(['$translateProvider', function($translateProvider) {
  $translateProvider.translations('en', {
    WELCOME: 'Welcome',
    MONITOR: 'Monitor',
    REFRESH: 'Refresh',
    USER: 'User',
    SESSION_TIMEOUT: 'Session timeout, please re-login',
    INVALIDATE_ACCOUNT: 'Invalidate account or wrong password',
    LOGOUT: 'Logout',
    LOGIN: 'Login',
    SETTING: 'Settings',
    CHANGE_PASSWORD: 'Change Password',
    PLEASE_LOGIN: 'Please Login',
    USERNAME: 'Username',
    PASSWORD: 'Password',
    REPASSWORD: 'Repeat Password',
    DESCRIPTION: 'Description',
    ADD_NEW_TABLE: 'Add New Table',
    ADD_NEW_SCHEMA: 'Add New Schema',
    ADD_NEW_USER: 'Add New User',
    UPDATE_USER: 'Update User Info',
    EDIT_SCHEMA: 'Edit Schema',
    NAME: 'Name',
    TYPE: 'Type',
    CONTENT: 'Content',
    INDEX_TYPE: 'Index Type',
    ROWKEY_EXPRESSION: 'Rowkey Expression',
    TABLE_EXPRESSION: 'Table Expression',
    CONSTANT: 'Constant',
    VARIABLE: 'Variable',
    FUNCTION: 'Function',
    CUSTOMIZE: 'Customize',
    SCHEMA: 'Schema',
    THE: 'the',
    TOTAL: 'total',
    STEP: 'step',
    STEPS: 'steps',
    SCHEMA_NAME: 'Schema Name',
    SCHEMA_TYPE: 'Schema Type',
    HBASE_ONLY: 'Data Storage & Simple Query',
    HBASE_ONLY_EXPLAIN: 'Provide columnar storage of data and query in rowkey level',
    HBASE_INDEXER_SOLR: 'Data Storage & Content Index',
    HBASE_INDEXER_SOLR_EXPLAIN: '提供数据列式存储及全字段内容索引，可通过内容索引实现全字段随机检索',
    HBASE_PHOENIX: 'Data Storage & Extend Query',
    HBASE_PHOENIX_EXPLAIN: '提供数据列式存储及Rowkey级别的SQL扩展查询',
    HBASE_SOLR_PHOENIX: 'SQL Extend Query & Content Index',
    HBASE_SOLR_PHOENIX_EXPLAIN: '提供数据列式存储、Rowkey级别的SQL扩展查询以及全字段内容索引',
    OPTIONAL_FIELDS: 'Optional Fields',
    COMPONENT: 'Component',
    WEIGHT: 'Weight',
    FIELDS: 'Fields',
    ADDED_FIELDS: 'Added Fields',
    EXPRESSION: 'Expression',
    TABLE: 'Table',
    TABLENAME: 'Table Name',
    INDEXER: 'Indexer',
    HOST: 'Host',
    SEARCH: 'Search',
    KEY: 'Key',
    VALUE: 'Value',
    CONFIG: 'Config',
    REGION_NUM: 'Region Number',
    REGION_NUM_EXPLAIN: 'Cannot be configured after table created',
    REGION_SPLIT: 'Region Split',
    SOLR: 'Solr',
    SOLR_SHARDS: 'Solr Shards',
    SOLR_SHARDS_EXPLAIN: 'Cannot be configured after table created',
    SOLR_REPLICAS: 'Solr Replicas',
    SOLR_REPLICAS_EXPLAIN: 'solr replicas, recommanded value is "2"',
    OK: 'OK',
    CANCEL: 'Cancel',
    NEXT: 'Next',
    NORMAL: 'Normal',
    ERROR: 'Error',
    PREV: 'Previous',
    PREV_WARN: 'Back to previous page will clear all parameters in this page',
    EDIT_TABLE_FIELDS: 'Edit Table Fields',
    FIELD_NAME: 'Field Name:',
    STORE_TYPE: 'Store Type:',
    CONTENT_FIELD: 'Content Field',
    INNER_FIELD: 'Inner Field',
    FIELD_INDEX: 'Field Index',
    INDEXED: 'Indexed',
    QUERY_FIELD: 'Query Field',
    ID_FORMATTER: 'ID Formatter',
    INTABLE_NAME: 'name',
    INTABLE_TYPE: 'type',
    INTABLE_SEPARATOR: 'separator',
    INTABLE_STORE_TYPE: 'store type',
    INTABLE_INDEXED: 'Indexed',
    INTABLE_INDEX_TYPE: 'index type',
    INTABLE_INNER_FIELD: 'inner field',
    INTABLE_CONTENT_FIELD: 'content field',
    INTABLE_QUERY_WEIGHT: 'query weight',
    INTABLE_OPERATION: 'operation',
    INTABLE_WEIGHT: 'weight',
    INTABLE_DISPLAY: 'display in search',
    DISPLAY: 'display',
    SELECT_TYPE: 'Select Type',
    SELECT_SCHEMA: 'Select schema',
    SELECT_INDEX_TYPE: 'Select index type',
    SELECT_FIELD: 'Select existed field',
    SELECT_FUNCTION: 'Select function',
    FILL_FUNCTION_ARGS : 'Please fill in arguments of function',
    SELECT_FIELD_STORE_TYPE: 'Select field store type',
    SELECT_FIELD_INDEX_TYPE: 'Select field index type',
    SELECT_FIELD_CONTENT_FIELD: 'Select existed content field',
    SELECT_FIELD_INNER_FIELD: 'Select existed inner field',
    SELECT_QUERY_FIELD: 'Select existed field to query',
    BASIC_INFO: 'Basic Info',
    ADD: 'Add',
    EDIT: 'Edit',
    DELETE: 'Delete',
    NOT_EDITABLE: 'Used',
    UNAVAILABLE: 'Unavailable',
    YES: 'Yes',
    NO: 'No',
    CONFIRMATION: 'Confirmation',
    WARNING: 'Warning',
    MODALMSG_FILL_IN_ALL: 'Please fill in all inputs marked as *',
    MODALMSG_NO_FIELDS: 'No fields of schema defined!',
    MODALMSG_NAME_INVALIDATE: 'Username should start with upper/lower case letter or underline and the length should be longer than 4',
    MODALMSG_NAME_IN_USE: 'Username already be used',
    MODALMSG_PASSWORD_NOT_EQUAL: 'Password and repeat-password not equal',
    MODALMSG_WEAK_PASSWORD: 'Password is invalidate, require numbers or letters only, length of password should be 8 at least',
    MODALMSG_QUERY_FIELD_TIP: 'Tips: Content fields or Fields typed as "text*" can be configured as query fields. Repeat query fields not allowed!',
    MODALMSG_CHOOSE_SCHEMA_INDEX_TYPE: 'Please choose index type of schema!',
    MODALMSG_INNER_NO_USE: 'Not all inner fields are used by fields!',
    MODALMSG_SCHEMA_IN_USE: 'Schema name already be used',
    MODALMSG_TABLE_IN_USE: 'Table name already be used',
    MODALMSG_SCHEMA_INVALIDATE: 'Invalidate schema name',
    MODALMSG_TABLE_INVALIDATE: 'Invalidate table name',
    MODALMSG_OPTION_FIELD_TIP: 'Field name started with underline or letters, more than 2 characters, no repeat field allowed',
    CONFIRM_LOGOUT: 'Are you sure to logout?',
    CONFIRM_ADD_TABLE: 'Create table now?',
    CONFIRM_ADD_USER: 'Create user now?',
    CONFIRM_UPDATE_USER: 'Change password?',
    CONFIRM_EDIT_TABLE: 'Change the schema of table now?',
    CONFIRM_DELETE_TABLE: 'Want to delete the table selected? All data related will be lost!',
    CONFIRM_DELETE_SCHEMA: 'Are you sure to delete the schema selected?',
    CONFIRM_DELETE_USER: 'Are you sure to delete the user selected?',
    CONFIRM_ADD_SCHEMA: 'Create schema now?',
    CONFIRM_EDIT_SCHEMA: 'Recreate schema now?',
    CONFIRM_DELETE_SCHEMA_ERR: 'There are tables belong to the schema. Delete all related tables first of all!',
    CONFIRM_EDIT_SCHEMA_ERR: 'There are tables belong to the schema. You can just edit fields of schema in "Table" panel.',
    CONFIRM_DELETE_USER_ERR: 'There are tables or schemas belong to the user. You must delete related objects first',
    CONFIRM_TITLE_CREATE_TABLE_ERROR: 'Error occur during creation of table',
    CONFIRM_TITLE_EDIT_TABLE_ERROR: 'Error occur during editing table',
    CONFIRM_TITLE_CREATE_SCHEMA_ERROR: 'Error occur during creation of schema',
    EMPTY: '(empty)',
    UNDEFINED: '(undefined)',
    NULL: '(null)',
    HELP_EXPRESSION_TITLE: 'Help to build an expression',
    HELP_EXPRESSION_CONTENT: 'Want to learn',
    HELP_EXPRESSION_LINK: 'more',
    ROWS: 'Rows',
    CONDITIONS: 'Conditions',
    ADVANCE_SEARCH: 'Advance Search',
    ADVANCE_CONFIG: 'Advanced options',
    WITH_HBASE: 'Hbase table existed',
    WITH_HBASE_YES: 'Hbase Column & Hbase Family are needed in Fields defination',
    HBASE: 'Hbase',
    HBASE_FAMILY: 'family',
    HBASE_COLUMN: 'column',
    PHOENIX: 'Phoenix',
    EXPLANATION: 'Explanation',
  });
}]);